scholar/urls.py
from django.contrib import admin
from django.urls import path,include
from scholarship import views as scholarship
from scholarship import urls as scholarship_urls
from userauth import urls as userauth_urls
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('scholarship/',include(scholarship_urls)),
    path('',scholarship.main),
    path('login/',include(userauth_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

scholarship/urls.py
from django.urls import path
from . import views

app_name = 'scholarship'

urlpatterns=[

    #######main##########
    path('main/',views.main , name='main'),
    #######scholarship detail######
    path('scholarship_detail/<slug:scholar_slug>/',views.scholarship_detail,name='detail'),

    path('my_scholar/',views.scholarship_my_scholar,name='my_scholar')
]

scholarship/models.py
from django.db import models
from unidecode import unidecode
from django.utils.text import slugify
from random import randint
# Create your models here.


class Scholar_content(models.Model):

    @staticmethod
    def randomtag():
        return str(randint(9,11))


    #장학이름
    scholar_name=models.CharField(max_length=200,primary_key=True,verbose_name='장학이름')
    #장학혜택
    scholar_reward=models.TextField(blank=True,verbose_name='장학혜택')
    #제출서류
    scholar_needs=models.TextField(blank=True,verbose_name='제출서류')
    #접수방법
    scholar_howto=models.TextField(blank=True,verbose_name='접수방법')
    #장학 문의 번호
    scholar_qna=models.TextField(blank=True,verbose_name='장학문의번호')
    #선발인원
    scholar_recruitment_num=models.PositiveIntegerField(verbose_name='선발인원')
    #모집기간
    scholar_application_start=models.DateTimeField(blank=True,null=True,verbose_name='제출기간 시작')
    scholar_application_end = models.DateTimeField(blank=True,null=True,verbose_name='제출기간 마지막')
    #장학재단명
    scholar_foundation_name=models.CharField(max_length=200,verbose_name='장학재단이름')
    #선발대상
    scholar_who_draft=models.TextField(blank=True,verbose_name='선발대상')
    #슬러그
    slug = models.SlugField(default='garbage',allow_unicode=True,max_length=100,verbose_name='슬러그')
    #썸네일
    thumb_nail = models.ImageField(default = 'default.png',verbose_name='썸네일')
    #양식
    form_file = models.FileField(verbose_name='양식업로드',null=True)

    def publish(self):
        self.save()

    def __str__(self):
        return self.scholar_name
    def my_slugify(self):
        self.slug = slugify(unidecode(self.scholar_name))

class Scholar_filter(models.Model):


    #####################
    KEYONGIDO='KEYNGIDO'
    SEOUL = 'SEOUL'
    BUSAN = 'BUSAN'
    DAEGOO = 'DAEGOO'
    INCHEON = 'INCHEON'
    DAEJUN = 'DAEJUN'
    ULSAN = 'ULSAN'
    KANGWONDO = 'KANGWONDO'
    CHUNGCHUNGBOOKDO = 'CHUNGCHUNGBOOKDO'
    CHUNGCHUNGNAMDO = 'CHUNGCHUNGNAMDO'
    JEOLABOOKDO='JEOLABOOKDO'
    JEOLANAMDO = 'JEOLANAMDO'
    KEYONGSANGBOOKDO = 'KEYONGSANGBOOKDO'
    KEYONGSANGNAMDO = 'KEYONGSANGNAMDO'
    SEJONG = 'SEJONG'
    JEJUDO = 'JEJUDO'


    Living_AREA_CHOICES=(
        (KEYONGIDO,'경기도'),
        (SEOUL,'서울특별시'),
        (BUSAN,'부산'),
        (DAEGOO,'대구'),
        (INCHEON,'인천'),
        (DAEJUN,'대전'),
        (ULSAN,'울산'),
        (KANGWONDO,'강원도'),
        (CHUNGCHUNGBOOKDO,'충청북도'),
        (CHUNGCHUNGNAMDO,'충청남도'),
        (JEOLABOOKDO,'전라북도'),
        (JEOLANAMDO,'전라남도'),
        (KEYONGSANGBOOKDO,'경상북도'),
        (KEYONGSANGNAMDO,'경상남도'),
        (SEJONG,'세종특별자치시'),
        (JEJUDO,'제주도')
    )
    ############################

    COMPLETION_SEMESTER_CHOICES=(
        (0,'아직 수료하지 않았습니다.'),
        (1,'1학기'),
        (2,'2학기'),
        (3,'3학기'),
        (4,'4학기'),
        (5,'5학기'),
        (6,'6학기'),
        (7,'7학기'),
        (8,'8학기'),
    )
    INCOME_LEVEL_CHOICES =(
        (0,'0분위'),
        (1,'1분위'),
        (2,'2분위'),
        (3,'3분위'),
        (4,'4분위'),
        (5,'5분위'),
        (6,'6분위'),
        (7,'7분위'),
        (8,'8분위'),
        (9,'9분위'),
        (10,'10분위'),
    )

    #id
    filter_id=models.OneToOneField(Scholar_content,on_delete=models.CASCADE,verbose_name='아이디')
    #성적
    filter_grade=models.FloatField(default=0,verbose_name='성적')
    #수료학기
    filter_completion_semester=models.PositiveSmallIntegerField(choices=COMPLETION_SEMESTER_CHOICES,default=0,verbose_name='수료학기')
    #소재지
    filter_living_area=models.CharField(max_length=200,choices= Living_AREA_CHOICES,null=True,default=None,verbose_name='소재지')
    #소득분위
    filter_income_level=models.PositiveSmallIntegerField(choices=INCOME_LEVEL_CHOICES,default=10,null=True,verbose_name='소득분위')
    #교내(true)/교외(false)
    filter_is_our_college=models.BooleanField(default=False,verbose_name='교내/교외')
    #특이사항
    filter_uniqueness=models.TextField(blank=True,null=True,verbose_name='특이사항')
    scholar_application_end=models.DateTimeField(blank=True,null=True,verbose_name='자동생성 제출기간 마지막')

    def save(self,*args,**kwargs):
        if self.filter_id:
            self.scholar_application_end = self.filter_id.scholar_application_end
        super(Scholar_filter,self).save(*args,**kwargs)



class Uniqueness(models.Model):
    u_ID=models.OneToOneField(Scholar_filter,on_delete=models.CASCADE,related_name='uniqueness')
    #다문화가정
    u_1=models.BooleanField(default=False,verbose_name='다문화가정')
    #기초생활수급
    u_2=models.BooleanField(default=False,verbose_name='기초생활수급자')
    #차상위계층
    u_3=models.BooleanField(default=False,verbose_name='차상위계층')
    #장애인
    u_4=models.BooleanField(default=False,verbose_name='장애인')
    #새터민
    u_5=models.BooleanField(default=False,verbose_name='새터민')
    #보훈대상자
    u_6=models.BooleanField(default=False,verbose_name='보훈대상자')
    #조부모가정
    u_7=models.BooleanField(default=False,verbose_name='조부모가정')
    #다자녀
    u_8=models.BooleanField(default=False,verbose_name='다자녀')
    #한부모
    u_9=models.BooleanField(default=False,verbose_name='한부모')
    #학생가장
    u_10=models.BooleanField(default=False,verbose_name='학생가장')
    #농어촌자녀
    u_11=models.BooleanField(default=False,verbose_name='농어촌자녀')

scholarship/forms.py
from django import forms
from . import models

class CreateScholarship(forms.ModelForm):
    class Meta:
        model = models.Scholar_content
        fields=['scholar_name','scholar_reward','scholar_needs','scholar_howto',
        'scholar_qna','scholar_recruitment_num','scholar_application_period',
        'scholar_foundation_name','scholar_who_draft','thumb_nail'
        ]

class CreateFilterScholarship(forms.ModelForm):
    class Meta:
        model = models.Scholar_fliter
        fields=[
            'filter_Grade','filter_completion_semester','filter_living_area',
            'filter_income_level','filter_is_our_college',
            'filter_uniqueness',
        ]

class CreateUniqueness(forms.ModelForm):
    class Meta:
        model = models.Uniqueness
        fields=[
            'u_1','u_2','u_3','u_4','u_5','u_6',
            'u_7','u_8','u_9','u_10','u_11'
        ]

scholarship/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.utils.text import slugify
from django.contrib import messages
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.http import HttpResponse
from .models import Scholar_content,Scholar_filter,Uniqueness
from django.db.models import Q
from django.core.files import File
import os
from scholar.settings import MEDIA_ROOT
# Create your views here.


def main(request):
    page = request.GET.get('page','1')
    page = int(page)
    scholars = Scholar_content.objects.all().order_by('scholar_application_end').reverse()
    num=5
    paginator = Paginator(scholars,num)
    try:
        p = paginator.page(page)
    except PageNotAnInteger:
        p = paginator.page(1)
    except EmptyPage:
        p = paginator.page(paginator.num_pages)
    #if page's number smaller than 5
    if paginator.num_pages < num:
        num= paginator.num_pages
    
    start_index = 1
    end_index = paginator.num_pages
    if p.number>5:
        start_index = p.number-5
    if paginator.num_pages > p.number+5:
        end_index = p.number+5
    
    page_range = range(start_index,end_index+1)
    return render(request, 'scholarship/main.html', {'scholars': p, 'page_range': page_range,
    'page_start_index':start_index,'page_end_index':end_index})

def scholarship_detail(request,scholar_slug):
    scholar = Scholar_content.objects.get(slug=scholar_slug)
    FILE_DIR = os.path.join(MEDIA_ROOT,str(scholar.form_file))
    return render(request,'scholarship/detail.html',{'scholar':scholar})

@login_required(login_url ='login/login')
def scholarship_my_scholar(request):
    instances = Scholar_filter.objects.exclude(Q(filter_grade__gt=request.user.profile.user_grade),
    Q(filter_completion_semester__gt=request.user.profile.user_completion_semester),
    Q(filter_income_level__lt=request.user.profile.user_income_level)).order_by('scholar_application_end').reverse()
    scholars={} 
    scholars=list(scholars)
    for instance in instances:
        i=0
        for attr_name in Uniqueness._meta.get_fields():
            print(attr_name)
            i+=1
            if getattr(instance.uniqueness,attr_name.name):
                if i==1:
                    continue
                elif i==2:
                    continue
                elif getattr(request.user.useruniqueness,attr_name.name):
                    scholars += list(Scholar_content.objects.filter(scholar_name=instance.filter_id.scholar_name))
                    break
            elif i==13:
                scholars += list(Scholar_content.objects.filter(scholar_name=instance.filter_id.scholar_name))
                break
    

    page = request.GET.get('page','1')
    page = int(page)
    num=5
    paginator = Paginator(scholars,num)
    try:
        p = paginator.page(page)
    except PageNotAnInteger:
        p = paginator.page(1)
    except EmptyPage:
        p = paginator.page(paginator.num_pages)
    #if page's number smaller than 5
    if paginator.num_pages < num:
        num= paginator.num_pages
    
    start_index = 1
    end_index = paginator.num_pages
    if p.number>5:
        start_index = p.number-5
    if paginator.num_pages > p.number+5:
        end_index = p.number+5
    
    page_range = range(start_index,end_index+1)
    return render(request, 'scholarship/my_scholar.html', {'scholars': p, 'page_range': page_range,
    'page_start_index':start_index,'page_end_index':end_index})

scholarship/templates/scholarship/detail.html
{% extends 'base_layout.html' %}
{% load static %}
    {% block content%}
    <div class="content-detail">
        <li class="list-detail">
            <img src="{{MEDIA_URL}}{{scholar.thumb_nail.url}}" alt="">
            <h1 class="title">{{scholar.scholar_name}}</h1>
            <ul><p class="detail-title">장학혜택:</p> {{scholar.scholar_reward}}</ul>
            <ul><p class="detail-title">선발대상:</p> {{scholar.scholar_who_draft}}</ul>
            <ul><p class="detail-title">접수방법:</p> {{scholar.scholar_howto}}</ul>
            <ul><p class="detail-title">제출서류:</p> {{scholar.scholar_needs}}</ul>
            <ul><p class="detail-title">선발인원:</p> {{scholar.scholar_recruitment_num}}</ul>
            <ul><p class="detail-title">모집기간:</p> {{scholar.scholar_application_start}}~{{scholar.scholar_application_end}}</ul>
            <ul><p class="detail-title">장학재단명:</p> {{scholar.scholar_foundation_name}}</ul>
            <ul><p class="detail-title">문의:</p> {{scholar.scholar_qna}}</ul>
            <ul><p class="detail-title">양식:</p>{%if scholar.form_file %}<a href="{{MEDIA_ROOT}}{{scholar.form_file.url}}">{{scholar.form_file}}</a>{% endif%}</ul>
        </li>
    </div>
    {% endblock %}

scholarship/templates/scholarship/main.html
{% extends 'base_layout.html' %}
    {% block content %}

    <div class="about">
        <h1>간편한 장학금</h1>
        <li>
            <ul>내 정보에 맞춰 받을 수 있는 장학금을 추천해드립니다.</ul>
        </li>
    </div>

    <div class="introduce">
        <h1>현재 장학금 리스트</h1>
    </div>
        <div class="scholar-content">
        {% for scholar in scholars%}
            <li class="scholar-list">
                <ul>
                <a class="btn-{{scholar.randomtag}}" href="{%url 'scholarship:detail' scholar.slug%}">{{scholar.scholar_name}}</a>
                </ul>
                <ul class="scholar-period">{{scholar.scholar_application_end}}까지 접수</ul>
            </li>
        {% endfor %}
        </div>
        </div>
        
    {# pagination #}
    <nav class="pagination">
        <ul class="pagination">
        {% if scholars.has_previous %}
            <li>
                <a href="?page={{ page_start_index }}">
                    <span>Prev</span>
                </a>
            </li>
        {% endif %}
        
        {% for i in page_range %}
            {% if i == scholars.number %}
            <li class="active"><span>{{ i }}</span></li>
            {% else %}
            <li class="active">
                <span><a href="?page={{ i }}">{{i}}</a></span>
            </li>
            {% endif %}
        {% endfor %}

        {% if scholars.has_next %}
            <li>
                <a href="?page={{ page_end_index}}">
                    <span>Next</span>
            </a>
            </li>
        {% endif %}
        </ul>
    </nav>
    {% endblock %}

scholarship/templates/scholarship/my_scholar.html
{% extends 'base_layout.html' %}
    {% block content %}

    <div class="my-scholar">
        <h1>내가 받을 수 있는 장학금</h1>
        {% for instance in scholars%}
        <div class="content">
        <li class="scholar">
        <a class="link" href="{% url 'scholarship:detail' instance.slug %}">
            <ul id="scholar-name">장학이름:{{instance.scholar_name}}</ul>
            <ul id="scholar-reward">장학혜택:{{instance.scholar_reward}}</ul>
            <ul id="scholar-recruitment">선발인원:{{instance.scholar_recruitment_num}}</ul>
            <ul id="scholar-application-period">모집기간:{{instance.scholar_application_start}}~{{instance.scholar_application_end}}</ul>
        </a>
        </li>
        </div>
        {% endfor%}
    </div>

    {# pagination #}
    <nav class="pagination">
        <ul class="pagination">
        {% if scholars.has_previous %}
            <li>
                <a href="?page={{ page_start_index }}">
                    <span>Prev</span>
                </a>
            </li>
        {% endif %}
        
        {% for i in page_range %}
            {% if i == scholars.number %}
            <li class="active-none"><span>{{ i }}</span></li>
            {% else %}
            <li class="active-href">
                <span><a href="?page={{ i }}">{{i}}</a></span>
            </li>
            {% endif %}
        {% endfor %}

        {% if scholars.has_next %}
            <li class="active-href">
                <a href="?page={{ page_end_index}}">
                    <span>Next</span>
            </a>
            </li>
        {% endif %}
        </ul>
    </nav>

    {% endblock %}