scholar/urls.py
from django.contrib import admin
from django.urls import path,include
from scholarship import views as scholarship
from scholarship import urls as scholarship_urls
from userauth import urls as userauth_urls
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('scholarship/',include(scholarship_urls)),
    path('',scholarship.main),
    path('login/',include(userauth_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

scholarship/urls.py
from django.urls import path
from . import views

app_name = 'scholarship'

urlpatterns=[

    #######main##########
    path('main/',views.main , name='main'),
    #######scholarship detail######
    path('scholarship_detail/<slug:scholar_slug>/',views.scholarship_detail,name='detail'),

    path('my_scholar/',views.scholarship_my_scholar,name='my_scholar')
]

userauth/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name= 'userauth'

urlpatterns =[
    path('login/',views.login_view, name='login'),
    path('signup/',views.signup_view,name='signup'),
    path('detail/',views.detail_view, name ='detail'),
    path('logout/',views.logout_view,name='logout'),
]

templates/base_layout.html
{% load static %}
{% load sass_tags %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8"> 
        <!---favicon-->
        <link rel="shortcut icon" href="{% static 'favicon_io/favicon.ico'%}">
        <link rel="apple-touch-icon" sizes="180x180" href="{{STATIC_ROOT}}favicon_io/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="{{STATIC_ROOT}}favicon_io/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="{{STATIC_ROOT}}favicon_io/favicon-16x16.png">
        <!--------------------------------------------------------->
        <link rel="stylesheet" href="{%sass_src 'scss/logo.scss' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'css/base.css'%}" type="text/css">
        <link rel="stylesheet" href="{%static 'js/logo.js'}">
        {%block script%}
        {% endblock%}

        
        <header>
            <div class="header-content">
            <ul class="list"><a href="{%url 'scholarship:main'%}"><img class="logo" id="logo" src="{%static 'img/logo.png'%}" alt=""></a></ul>
            <li class="header-list">
                <ul class="list"><a href="{%url 'scholarship:main'%}">장학금</a></ul>
                {% if user.is_authenticated%}
                <ul class="list"><a href="{% url 'scholarship:my_scholar'%}">내가 받을 수 있는 장학금</a></ul>
                {% else%}
                <ul class="list"><a href="{% url 'userauth:login'%}">내가 받을 수 있는 장학금</a></ul>
                {% endif%}
                {% if user.is_authenticated%}
                <ul class="list"><a href="{%url 'userauth:logout'%}">로그아웃</a></ul>
                <ul class="list"><a href="{% url 'userauth:detail' %}">상세정보</a></ul>
                {% else %}
                <ul class="list"><a href="{% url 'userauth:login' %}">로그인</a></ul>
                <ul class="list"><a href="{% url 'userauth:signup'%}">회원가입</a></ul>
                {% endif%}                        
            </li>
            </div>
        </header>
    </head>

    <body>

        {% block content%}
        {% endblock%}
    </body>

    <footer>

    </footer>
</html>